backend:
  name: git-gateway
  branch: main

site_url: "https://tartil-quran.netlify.app"

media_folder: "assets"
public_folder: "/assets"

collections:
  - name: "content"
    label: "Content"
    folder: "content"
    create: true
    format: "frontmatter"
    extension: "html"
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "code", default_language: "html"}