backend:
  name: git-gateway
  branch: main

site_url: "https://tartil-quran.netlify.app"

media_folder: "assets"
public_folder: "/assets"
collections:
  - name: "content"
    label: "Content"
    folder: "content"
    create: true
    extension: "html"         
    format: "frontmatter"      
    identifier_field: title      
    slug: "{{slug}}"
    fields:
      - { label: "ID", name: "id", widget: "hidden", default: "{{uuid}}" }
      - { label: "Title", name: "title", widget: "string" }
      - label: "Body (HTML)"
        name: "body"
        widget: "markdown"
        hint: "يمكنك كتابة HTML و Markdown هنا"
        modes: ['raw']  # يُظهر الكود الخام