backend:
  name: git-gateway
  branch: main

media_folder: "assets"
public_folder: "/assets"

site_url: "https://tartil-quran.netlify.app"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "index.html"    # تم نقل الملف للجذر
        label: "Home Page"
        name: "home"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Content", name: "body", widget: "html" }  # HTML بدل Markdown
