backend:
  name: git-gateway
  branch: main

site_url: "https://tartil-quran.netlify.app"

media_folder: "assets"
public_folder: "/assets"

collections:
  - name: "content"
    label: "Content"
    folder: "content"
    create: true
    extension: "html"          # نحفظ كـ .html
    format: "frontmatter"      # Frontmatter + body
    identifier_field: id       # أو id لو تحب
    slug: "{{slug}}"
    fields:
      #- {label: "Title", name: "title", widget: "string"}
      #- {label: "Body", name: "body", widget: "markdown"}
      - { label: "ID", name: "id", widget: "hidden", default: "{{uuid}}" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body (HTML)", name: "body", widget: "code", default_language: "html" }

      