backend:
  name: git-gateway
  branch: main

site_url: "https://tartil-quran.netlify.app"

media_folder: "assets"
public_folder: "/assets"

collections:
  - name: "content"
    label: "Content"
    folder: "content"
    create: true
    extension: "html"
    format: "frontmatter"
    # identifier_field: id
    slug: "{{title}}"
    editor:
      preview: false
    fields:
      - { label: "ID", name: "id", widget: "hidden", default: "{{uuid}}" }
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Body (HTML)", name: "body", widget: "code", default_language: "html", preview: false }
